# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_reverse.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(400, 500)
        MainWindow.setMinimumSize(QtCore.QSize(400, 500))
        MainWindow.setMaximumSize(QtCore.QSize(400, 500))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 400, 500))
        self.frame.setMinimumSize(QtCore.QSize(400, 500))
        self.frame.setMaximumSize(QtCore.QSize(400, 500))
        self.frame.setStyleSheet("background-color: #202020;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEditSourceText = QtWidgets.QLineEdit(self.frame)
        self.lineEditSourceText.setGeometry(QtCore.QRect(20, 120, 361, 61))
        self.lineEditSourceText.setStyleSheet("background-color: #C0C0C0;\n"
"font-size: 16px;\n"
"border-radius: 10px;\n"
"border: 1px solid black;\n"
"padding: 10px;\n"
"color: black;\n"
"font-weight: bold;")
        self.lineEditSourceText.setObjectName("lineEditSourceText")
        self.btnReverseText = QtWidgets.QPushButton(self.frame)
        self.btnReverseText.setGeometry(QtCore.QRect(60, 410, 271, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnReverseText.setFont(font)
        self.btnReverseText.setStyleSheet("border-radius: 10px;\n"
"color: black;\n"
"background-color: #DCDCDC;\n"
"font-weight: bold;")
        self.btnReverseText.setObjectName("btnReverseText")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 401, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #ffffff;\n"
"background-color: #A9A9A9;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(0, 80, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #ffffff;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(0, 220, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #ffffff;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.lineEditReverseText = QtWidgets.QLineEdit(self.frame)
        self.lineEditReverseText.setGeometry(QtCore.QRect(20, 260, 361, 61))
        self.lineEditReverseText.setStyleSheet("background-color: #C0C0C0;\n"
"font-size: 16px;\n"
"border-radius: 10px;\n"
"border: 1px solid black;\n"
"padding: 10px;\n"
"color: black;\n"
"font-weight: bold;")
        self.lineEditReverseText.setReadOnly(True)
        self.lineEditReverseText.setPlaceholderText("")
        self.lineEditReverseText.setObjectName("lineEditReverseText")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Реверс текста"))
        self.lineEditSourceText.setPlaceholderText(_translate("MainWindow", "Введите текст"))
        self.btnReverseText.setText(_translate("MainWindow", "ОБРАБОТАТЬ ТЕКСТ"))
        self.label.setText(_translate("MainWindow", "РЕВЕРС ТЕКСТА"))
        self.label_2.setText(_translate("MainWindow", "Оригинальный текст"))
        self.label_3.setText(_translate("MainWindow", "Обработанный текст"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
